title: R. L. GARTH
logo: /assets/img/me.png
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
instagram: https://www.instagram.com/rlgarth/
insta_icon: /assets/img/Instagram_Glyph_Black.svg
redbubble: https://www.redbubble.com/people/creepingcards/shop
rb_icon: /assets/img/redbubble.svg
email: author@rlgarth.com
email_icon: /assets/img/email_icon.svg